sudo: false
dist: trusty
language: generic
install: 
    - wget https://github.com/gohugoio/hugo/releases/download/v0.39/hugo_0.39_Linux-64bit.tar.gz
    - tar -zxvf hugo_0.39_Linux-64bit.tar.gz
    - chmod +x hugo
script:
    - ./hugo -t casper
deploy:
    local_dir: public
    repo: cizel/cizel.github.io
    target_branch: master
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    email: i.cizel.cn
    name: cizel
    on:
        branch: master
