sudo: false
language: go
go:
    - master
install: 
    - go get -v github.com/gohugoio/hugo
script:
    - hugo
deploy:
    local_dir: public
    repo: cizel/cizel.github.io
    target_branch: master
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    email: i.cizel.cn
    name: cizel
    on:
        branch: master
