baseURL = "http://blog.cizel.cn"
languageCode = "en-us"
title = "Cizel's Blog"
copyright = "All rights reserved @ 2018"
disqusshortname = "cizel"
paginate = 5
pluralizelisttitles = false
theme = "hugo-theme-casper"

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/"
weight = -120
[[menu.main]]
name = "Github repos"
pre = "<h3>Follow me</h3>"
url = "https://github.com/cizel"
weight = 100

[params]
author = "cizel"
authorlocation = "Beijin"
authorwebsite = "http://www.cizel.cn"
authorbio = "IT software and Security Engineer, Open source enthusiast."
cover = "http://static.cizel.cn/2018-04-21-macpro.jpg"
description = "Cizel's Blog"
githubName = "cizel"
googleAnalyticsUserID = "UA-79101-12"
hideHUGOSupport = false
logo = "http://static.cizel.cn/2018-04-21-ghost.png"
twitterName = "vjeantet"
[permalinks]
post = "/:slug/"
[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"
