baseURL = "http://blog.cizel.cn"
languageCode = "en-us"
title = "Cizel's Blog"
copyright = "All rights reserved @ 2018"
disqusshortname = "cizel"
paginate = 5
pluralizelisttitles = false
theme = "casper"

[params]
author = "cizel"
authorlocation = "Beijin"
authoravatar = "https://static.cizel.cn/2018-04-21-a.jpg"
authorwebsite = "http://www.cizel.cn"
authorbio = "IT software and Security Engineer, Open source enthusiast."
cover = "https://static.cizel.cn/2018-04-21-macpro.jpg"
description = "如何成为一个很厉害的人"
githubName = "cizel"
hideHUGOSupport = true
logo = "https://static.cizel.cn/2018-04-21-ghost.png"
[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"
