baseURL = "http://blog.cizel.cn"
languageCode = "cn"
title = "Cizel's Blog"
copyright = "All rights reserved @ 2018"
disqusshortname = "cizel"
paginate = 5
pluralizelisttitles = false
theme = "casper"

[[menu.main]]
identifier = "Home"
name = "Home"
url = "/"
weight = -120
[[menu.main]]
name = "Github repos"
pre = "<h3>Follow me</h3>"
url = "https://github.com/cizel"
weight = 100

[params]
author = "cizel"
authorlocation = "Beijin"
authoravatar = "https://static.cizel.cn/2018-04-21-a.jpg"
authorwebsite = "https://www.cizel.cn"
authorbio = "IT software and Security Engineer, Open source enthusiast."
cover = "https://static.cizel.cn/2018-04-21-macpro.jpg"
description = "如何成为一个很厉害的人"
githubName = "cizel"
hideHUGOSupport = true
logo = "https://static.cizel.cn/2018-04-21-ghost.png"
cdnURL = "https://static.cizel.cn" 

[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"
