baseURL = "https://www.cizel.cn"
title = "Cizel's Blog"
enableRobotsTXT = true
enableEmoji = true
theme = "jane"

hasCJKLanguage = true     # has chinese/japanese/korean ? # 自动检测是否包含 中文\日文\韩文
paginate = 6                                              # 首页每页显示的文章数
rssLimit = 20             # Limit Entry Count to Rss file # 限制 Rss 文章输出数量
disqusShortname = ""      # disqus_shortname
googleAnalytics = ""      # UA-XXXXXXXX-X
copyright = "<a href=\"https://www.cizel.cn\">Cizel</a>"            # default: author.name ↓        # 默认为下面配置的author.name ↓
# uglyURLs = true         # more info: https://gohugo.io/content-management/urls/#ugly-urls

# Highlight options. See https://gohugo.io/content-management/syntax-highlighting/
PygmentsCodeFences = true # Enable syntax highlighting with GitHub flavoured code fences
PygmentsUseClasses = true # Use CSS classes to format highlighted code
PygmentsCodefencesGuessSyntax = true
PygmentsOptions = "linenos=table"

# language support # en / zh-cn / other... translations present in i18n/
defaultContentLanguage = "zh-cn"           # Default language to use
[languages.zh-cn]
  languageCode = "zh-cn"

[author]                  # essential                     # 必需
  name = "Cizel"

[sitemap]                 # essential                     # 必需
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]             # config your menu              # 配置目录
  name = "首页"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "归档"
  weight = 20
  identifier = "archives"
  url = "/post/"
[[menu.main]]
  name = "便签"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "分类"
  weight = 40
  identifier = "categories"
  url = "/categories/"
[[menu.main]]
  name = "记录"
  weight = 50
  identifier = "daily-notes"
  url = "/daily-notes/"

[[menu.main]]
  name = "关于"
  weight = 60
  identifier = "about"
  url = "/about/"

[params]
  debug = false             # If true, load `eruda.min.js`. See https://github.com/liriliri/eruda
  # uglyURLs = true          # You must set true after use uglyURLs in site (above). because $.Site.UglyURLs can not import.
  since = "2016"            # Site creation time          # 站点建立时间
  homeFullContent = false   # if false, show post summaries on home page. Othewise show full content.
  rssFullContent = true     # if false, Rss feed instead of the summary

  # site info (optional)                                  # 站点信息（可选，不需要的可以直接注释掉）
  logoTitle = "Cizel Blog"        # default: the title value    # 默认值: 上面设置的title值
  keywords = ["Blog", "Cizel的博客", "Cizel", "PHP", "Go"]
  description = "爱编程，爱安全，爱生活 - Cizel.cn"


  # paginate of archives, tags and categories             # 归档、标签、分类每页显示的文章数目，建议修改为一个较大的值
  archive-paginate = 20

  # paginate style, default use numbered pagination links
  # if true, use original "Previous" and "Next" links.
  # paginateOriginalStyle = true

  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse = "2006-01-02"

  # show word count and read time ?                       # 是否显示字数统计与阅读时间
  moreMeta = true

  # 一些全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能，在 archetypes/default.md 查看更多信息。
  # Some global options, you can also close or open something in front matter for a single post, see more information from `archetypes/default.md`.
  toc = true                                                                            # 是否开启目录
  photoswipe = true         # see https://github.com/dimsemenov/PhotoSwipe            # 是否启用PhotoSwipe（图片可点击）
  bootcdn = false           # In china. @Deprecated: use [params.publicCDN]             # 是否使用bootcdn(@Deprecated: 请使用[params.publicCDN])
  mathjax = false           # see https://www.mathjax.org/                              # 是否使用mathjax（数学公式）
  contentCopyright = '<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/deed.zh"><i class="fa fa-creative-commons"></i> 署名-非商业性使用 4.0 国际 </a>'     # e.g. '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a>'

  changyanAppid = ""        # Changyan app id             # 畅言
  changyanAppkey = ""       # Changyan app key
  tencent_analytics = ""    # Tencent Analytics
  baidu_push = false        # baidu push                  # 百度
  baidu_analytics = ""      # Baidu Analytics
  baidu_verification = ""   # Baidu Verification
  google_verification = ""  # Google_Verification         # 谷歌

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  customCSS = []            # if ['custom.css'], load '/static/css/custom.css' file
  customJS = []             # if ['custom.js'], load '/static/js/custom.js' file

  # enable 'fork me on github', see https://blog.github.com/2008-12-19-github-ribbons/
  # forkMeOnGithub = "https://github.com/xianmin/hugo-theme-jane"

  [params.publicCDN]        # load these files from public cdn                          # 启用公共CDN，需自行定义
    enable = false
	jquery = '<script src="https://cdn.cizel.cn/dist/js/jquery.min.js"></script>'
	slideout = '<script src="https://cdn.cizel.cn/dist/js/slideout.min.js"></script>'
	gitmentJS = '<script src="https://cdn.cizel.cn/dist/js/gitment.browser.min.js"></script>'
	gitmentCSS = '<link rel="stylesheet" href="https://cdn.cizel.cn/dist/css/default.min.css">'

  [params.utteranc]         # utteranc is a comment system based on GitHub issues. see https://utteranc.es
    enable = true
    repo = "cizel/cizel-blog"    # The repo to store comments
    issueTerm = "og:title"

  [params.gitment]          # Gitment is a comment system based on GitHub issues. see https://github.com/imsun/gitment
    owner = ""              # Your GitHub ID
    repo = ""               # The repo to store comments
    clientId = ""           # Your client ID
    clientSecret = ""       # Your client secret


  [params.reward]                                         # 文章打赏
    enable = false
    wechat = "/path/to/your/wechat-qr-code.png"           # 微信二维码
    alipay = "/path/to/your/alipay-qr-code.png"           # 支付宝二维码

  [params.social]                                         # 社交链接
    a-email = "mailto:i@cizel.cn"
    g-github = "http://github.com/cizel/"

# jsonfeed support
# more information: https://github.com/xianmin/hugo-theme-jane/issues/23
# to have json output it's necessary to uncomment this block of code and create a index.jsonfeed.json template, using hugo template specs
# [outputs]
#   home = ["html", "jsonfeed","rss"]
#   page = ["html"]
#
# [outputFormats]
# [outputFormats.jsonfeed]
#   mediaType = "application/json"
#   baseName = "feed"
#   isPlainText = true


# multilingual support example
# [langusges]
# [languages.en]
#   title = "Jane - A simple theme for Hugo"
#   weight = 1
# [languages.zh-cn]
#   title = "Jane —— 一个简洁的 Hugo 主题"
#   weight = 2
