---
baseURL: http://blog.cizel.cn
languageCode: cn
title: "Cizel's Blog"
copyright: "All rights reserved @ 2018"
paginate: 10
pluralizelisttitles: false
theme: casper

menu:
    - main:
        identifier: "Home"
        name: "Home"
        url: "/"
        weight: 100

params:
    author: "cizel"
    authorlocation: "Beijing, China"
    authoravatar: "https://static.cizel.cn/2018-04-21-a.jpg"
    authorwebsite: "www.cizel.cn"
    authorbio: "IT software and Security Engineer, Open source enthusiast."
    cover: "https://static.cizel.cn/2018-04-21-macpro.jpg"
    description: "如何成为一个很厉害的人"
    githubName: "cizel"
    hideHUGOSupport: true
    logo: "https://static.cizel.cn/2018-04-21-ghost.png"
    cdnURL: "https://static.cizel.cn" 

sitemap:
    ChangeFreq: ""
    Filename: "sitemap.xml"
    Priority: "-1"
